### ISSUE TITLE
Slow backwards playback stutters on Windows

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#234]
**Describe the bug**
Backwards playback between -1/32 and -1/2, inclusive, cause the video to stutter during the periods where the frame should be still.

**To Reproduce**
1. Add video and shuttle to one of the affected playback speeds

**Expected behavior**
No jitter. Frame should stay still until time for update.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc3
 - Plugin: FFMPEG

**Comment by TheoWolf** [comment]
This is the normal behavior of the FFmpeg player, the Datavyu backward playback is based on a seek playback which is faking the playback by triggering consecutive seeks to a timestamp (backward playback is not implemented in the FFmpeg player). However, the FFmpeg, in order to perform an accurate seek need to jump to the next frame after seeks which is causing stuttering during backward seeks (because of the frame jump)

**Comment by TheoWolf** [comment]
This will not be fixed, because of the low priority of the backward playback feature
