### ISSUE TITLE
Menubar items don't highlight on mouse hover

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#274]
**Describe the bug**
Drop-down menubar items do not highlight when you hover your mouse over selections.

**To Reproduce**
1. Add a video with FFMPEG or open a spreadsheet containing an FFMPEG video
2. Click any menubar item (e.g., File, Spreadsheet)
3. Hover mouse over drawer items

**Expected behavior**
Item the mouse is hovering over should be highlighted to indicate selection.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Datavyu version 1.5.0rc5

**Additional context**

**Comment by sh0sh1n** [comment]
@TheoWolf this is actually much more of a nuisance than I originally thought. Running scripts from the drop-down menu is nearly impossible because mouse clicks don't register properly on the menu items.

**Comment by TheoWolf** [comment]
@sh0sh1n Is this something specific to 1.5.0 version or used to be in previous versions?

**Comment by sh0sh1n** [comment]
Introduced in 1.5.0. Was not present in 1.4.2

**Comment by sh0sh1n** [comment]
This only happens with the FFMPEG plugin. Editing reproduce steps to indicate this. Also, the Help menubar items work fine.

**Comment by TheoWolf** [comment]
This is probably due to the SDL Window (natively using AppKit) running on the Main thread and interfering with other AppKit components.

**Comment by TheoWolf** [comment]
This commit https://github.com/databrary/datavyu/commit/8d479d7d42d94c8b619e005aa23960c3fb5cef85 is not a final fix.
The Java Menu bar seems to work when the FFmpeg (SDL) Window is selected, a temporary fix is to raise the SDL window (if any) when using Datavyu menu.

**Comment by TheoWolf** [comment]
The problem of the Menu bar on Mac OS is related to the SDL2 library that is natively using AppKit and running on the Main thread since we are calling the SDL window via a JNI bridge, the JVM is attaching java menus displayed on the Mac OS bar using the System property "apple.laf.useScreenMenuBar" to the SDL window, therefore, the menu bar works normally when the SDL window is in Focus.
**Note:** The Java menu bar works fine when "apple.laf.useScreenMenuBar" property is off, the menu will show on the Java Frame and interaction will be normal.
