### ISSUE TITLE
Question: Is changing the jog step size by adjusting fps ok, or does it lead to problems with playing the videos etc?

### ISSUE THREAD

**Issue by juliusverrel** [databrary/datavyu#342]
We'd like to code events (tics in Tourette syndrome), but frame-precision timing is not essential. We are interested in timing precision ~0.5s. Using a larger jog interval helps avoid unnecessary decisions about when the event happens. This can apparently be achieved by adjusting the fps (e.g. changing from 30 to 5). But I'm unsure whether this might create problems e.g. during video playback, marking cells, etc. 

System: Windows 10, datavyu 1.3.7, vlc plugin (this seems to work best; unable to install the current dev release)

**Comment by TheoWolf** [comment]
@jperricone Can you please get in touch!

**Comment by jperricone** [comment]
@juliusverrel Changing the fps parameter will not affect video playback. It will affect the amount of time that the jog command changes the video timer (e.g., 5 fps -> 200 ms) as you pointed out. The only downside is that if the video is encoded at a higher frame rate than the fps you specify, there will be "frame rounding" where the video finds the nearest frame to the current time point that you hop to. Please let me know if you have any additional questions.

**Comment by jperricone** [comment]
@juliusverrel That frame rounding will only occur at the level of +/- 1 frame , which is not essential for your analyses anyway.

**Comment by juliusverrel** [comment]
@jperricone thank you for the fast and very helpful answer! All the best, Julius

**Comment by jperricone** [comment]
@juliusverrel I realized that what I said was misleading. As soon as you set the steps per second/fps parameter, your video timer can only take on time values in multiples of 1/fps rounded. So if you set it to 30 fps, the timer will go 33 ms, 66 ms, 99 ms, 1 s 32 ms, ..., 990 ms, 1 s 23 ms, etc. Whatever onset/offset you mark will have to be included in this set of values. So when you set the fps to be smaller to avoid unnecessary frame-by-frame decisions, like to 5 fps for example, your timer can only equal 200 ms, 400 ms, 600 ms, etc., and therefore your onsets/offsets are constrained to these values. There will be frame rounding still (presumably your video is encoded at fps > 5 fps) but you may lose as many as 33 frames (if fps original = 30) seeing as the actual moment could be 1 s 32 ms (starting in increments of 33 frames) whereas at 5 fps you are forced to mark 1000 ms. Still, losing 33 ms is small compared to the the half-second resolution that matters to you, I just wanted to clarify the answer I gave.

**Comment by juliusverrel** [comment]
@jperricone That makes sense, if I understand correctly I might even be off by up to 99ms (if the event takes place at, say, 1098ms, the cell would start at 1000ms. But as you write, that's not an issue for my application case.

(you write "you may lose as many as 33 frames"; I think you mean "33 ms"?)

**Comment by jperricone** [comment]
@juliusverrel Whoops, yes I meant 33 ms - thanks for catching that. Let's say your video is encoded at 30 fps originally. When you jog through the video in 200 ms increments, at t = 200 ms the frame that's displayed will actually correspond to t = 198 ms (the closest multiple of 33 ms). At 400 ms, it will correspond to t = 396 ms, and so on. I think the worst case scenario is actually a 16 ms difference because there are always multiples on both sides. For example at 1600 ms, the closest multiple of 33 ms is 1584 ms. So regardless of how coarse you set the fps parameter, the frame that is displayed will always be true to the video +/- 1 frame at original frame rate.  However, when you debate between setting an onset at 1200 ms vs. 1400 ms, there are ~6 frames (200/33) that occurred between the frames you see. Hence your important original point that the behavior is not meaningfully changing over those smaller jog intervals. I think by bringing up frame rounding I distracted from the more significant consequence of increasing the jog interval, which is that you may no longer catch meaningful changes in behavior, though I am glad we clarified all this anyway. Please let me know if any of this is unclear. Thanks!
