### ISSUE TITLE
Adding Cells in the middle of column 

### ISSUE THREAD

**Issue by ahreese** [databrary/datavyu#372]
I previously had an issue with this with the unstable release, but after downloading the stable version of datavyu the problem didn't present itself for a while until now. 

I have a MacBook Air 2019 with osCatalina v10.15.6. When I try to add a new cell in a column, it adds one to either the row above or some other random row in that particular column.

**Comment by tiger980303** [comment]
Hi Annabelle,

Thanks for contacting Datavyu Support once again. When you're adding in a new cell, how are you going about that? Are you using the "Enter" key, "numpad 0" key, or clicking in the mouse? Datavyu does not create a cell based on the location at which your selection it's at, but rather it creates a cell based on the timestamp. It's possible that your cells are created out of place due to the timing of the cells. If this is not the case, I'll be happy to discuss this further.


Thanks,
Tiger
