### ISSUE TITLE
Quicktime 7.7.6 no longer available

### ISSUE THREAD

**Issue by Ally12345678** [databrary/datavyu#376]
Hi! I'm on a Windows 10 computer and am new to Datavyu. The instructions for downloading say to use Quicktime 7.7.6, but the link provided no longer works and I cannot find this version of quicktime from a reputable source. I downloaded version 7.7.9, but am having a lot of issues opening and viewing videos in Datavyu, and although I can sometimes open the video, it freezes if I try to do anything other than watch the video straight through.

**Comment by tiger980303** [comment]
Dear Ally12345678,
Thank you for contacting Datavyu Support. Can you please tell me your full name, the name of your PI (or if you are the PI in your lab), and your institution? We’re keeping track of the kinds of questions people have and a list of the people who request Datavyu tech support.

My apologies if you have recently contacted us. Please reply with your full name and if this is related to your last question and we will address your new Datavyu question.

Many thanks,
Tiger
Datavyu Support Team

**Comment by Ally12345678** [comment]
Hi Tiger,

My name is Allyson S. Masters, I work under Kathy Hirsh-Pasek at Temple
University.

This is my first question/issue with Datavyu.

Best,
Ally

**Comment by tiger980303** [comment]
Hi Ally,

Because you are running on a Windows OS, you are not required now to install/run QuickTime to use Datavyu. Our apologies if the information on the website is not working properly, we are currently working to update everything so that all the information is correct. 

For your issue specifically, which version of Datavyu are you using? If you are using Datavyu 1.3.7, I would recommend that you use the JavaFX plug in when you are adding in your video. On the "select file" pop up window after you hit "Add Data", there should be a drop down options to select the "Plugin". If there is no options, close the pop up window and hit "Add Data" again, it should be there now. Select "JavaFX" and it should work. If you are using Datavyu 1.5.1, there should be no need to select any plugin as there is only 1 plugin available to Windows OS. Both version will not require QuickTime to be installed.

Let me know if you have any other questions!

Thanks,
Tiger

**Comment by Ally12345678** [comment]
Hi Tiger,

Thank you, that fixed the opening issue but then the functionality was
limited (skipping forward and back caused the video to freeze and only the
audio to run). However, your answer reminded me that you have other
versions, and I'm happy to report that Datavyu 1.5.1 works very well.

Ally

**Comment by tiger980303** [comment]
Hi Ally,

We're sorry that our current stable version 1.3.7 is not working as well as you'd like, but I am glad to hear that our developmental version is working very well for you! Please don't hesitate to reach out to us if you encounter any issues regarding Datavyu.

Thanks,
Tiger
